<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Darkmount.Dock\Darkmount.Dock.csproj" />
    <ProjectReference Include="..\..\src\Darkmount.Keyboard\Darkmount.Keyboard.csproj" />
  </ItemGroup>
</Project>
